version: '2.6'

services:
 patients:
  container_name: db-patients
  restart: 'always'
  ports: 
   - 5432:5432
  environment:
   - POSTGRES_DB=patients 
   - POSTGRES_PASSWORD=1111
   - POSTGRES_USER=postgres
  image: postgres:alpine
  build:
   context: .
   dockerfile: docker/db/Dockerfile
  volumes:
   - ./postgres-data:/var/lib/postgresql/data
   - ./resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
   
 server:
  restart: always
  ports:
   - 8080:8080
   - 8081:8081
  build: 
   context: .
   dockerfile: docker/app/Dockerfile
  depends_on:
   - patients
