name: patients_test_build_deploy
on: 
 push:
  branches: 
   - 'main'
jobs:
 build:
  runs-on: ubuntu-latest
  permissions: 
   contents: read
   packages: write 
  steps:
    -
     name: Checkout
     uses: actions/checkout@v3
    -
     name: Login to Docker Hub
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
     name: Run Database
     run: docker run -e POSTGRES_PASSWORD=1111 -p 5432:5432 -d nikitasinc/db_tasks
    -
     name: Prepare java
     uses: actions/setup-java@v3
     with:
      java-version: '11'
      distribution: 'adopt'
    -
     name: Install clojure tools
     uses: DeLaGuardo/setup-clojure@3.5
     with:
      cli: 'latest'
    -
     name: Run Tests
     run: clojure -X:test
    -
     name: Build Uberjar
     run: clojure -T:build uber
    -
     name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1
    -
     name: Build and push app
     uses: docker/build-push-action@v2
     with:
      context: .
      file: ./docker/app/Dockerfile
      push: true
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clojure-patients-app:latest
    -
     name: Build and push app
     uses: docker/build-push-action@v2
     with:
      context: .
      file: ./docker/db/Dockerfile
      push: true
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/db_patients:latest
  
   
